server:
  port: ${PORT:8080}

spring:

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PosgreSQL94Dialect
    generate-ddl: true
  datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/queueDb
      username: postgres
      password: 12345
      driverClassName: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: myfirstcalculatorapp@gmail.com
    password: tutugafarli
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
