server:
  port: ${PORT:8080}

spring:

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
